version: "2"

volumes:
  # used by the db container to store mysql content
  db: {}
  # used by the node container to cache node_modules
  modules: {}

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./site/public/:/var/www/site/
      - ./legacy/cal/:/opt/legacy/cal/
      - ./backend/www/:/opt/backend/www/
      - "${EVENTIMAGES}:/opt/backend/eventimages"
      - ./services/nginx/:/opt/nginx/
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ${LETSENCRYPT_WEBROOT}:/tmp/letsencrypt-auto
    # shift.conf references the php and node ports
    # (ex. proxy_pass http://node:3080 )
    # so it needs links to be able to resolve those names
    links:
      - php
      - node
    ports:
      - "${NGINX_HTTPS_PORT}:443"
      - "${NGINX_HTTP_PORT}:80"
    entrypoint: /opt/nginx/entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]

  db:
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
    volumes:
      - db:/var/lib/mysql/
    ports:
      - 3306

  php:
    build: ./services/php
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - SHIFT_DOMAIN
      - NGINX_HTTPS_PORT
      - CAL_ADMIN_PASSWORD
      - SHIFT_EMAIL_LOG
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASS
      - SMTP_LOGIN
      - SMTP_DOMAIN
    links:
      - db
    volumes:
      - ./backend/:/opt/backend/
      - ./services/php/:/opt/php/
      - ./legacy/:/opt/legacy
    entrypoint: /opt/php/entrypoint.sh
    command: php-fpm

  node:
    restart: always
    image: node:20.11.1-slim
    # use the local logging driver for log storage and rotation
    # WARNING: doesnt work on production, reports:
    #  no logs are available with the 'local' log driver
    # https://docs.docker.com/config/containers/logging/local/
    # logging:
    #  driver: local
    links:
      - db
    environment:
        # these pull from the host environment
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_HOST
        - SHIFT_DOMAIN        # used for generating sharable links
        - NGINX_HTTPS_PORT    # used for generating sharable links
        - SHIFT_IMAGE_DIR     # event images
        - SMTP_HOST
        - SMTP_USER
        - SMTP_PASS
    # by default the node image will run "node"
    # https://github.com/nodejs/docker-node/blob/main/docker-entrypoint.sh
    # override to run npm start; which auto installs from package-lock.json
    command: npm start
    working_dir: /shift
    volumes:
      # map the shift node code and package files;
      # and attach to the volume for its modules.
      - ./app:/shift/app/
      - ./tools:/shift/tools/
      - ./package.json:/shift/package.json:ro
      - ./package-lock.json:/shift/package-lock.json:ro
      - modules:/shift/node_modules/

      # provide access to images:
      # the left-hand side is the host directory
      # the right-hand side has to be SHIFT_IMAGE_DIR
      # todo: change the host side to a named volume?
      # fix: can the rhs here use the environment var?
      - ./backend/eventimages/:/opt/backend/eventimages/

      # DEACTIVATED: access for email log:
      # email logging disabled has been disabled in emailer.js
      # console logging being used instead re: "./shift logs node"
      # - ./services/node/:/opt/node/
