const allViews = require("server/v2/schema/allViews");
const { allTables, extraKeys } = require("server/v2/schema/allTables");
const TableMaker = require('server/util/tableMaker');

module.exports = {
  // 'image', 'series', etc.
  tableNames: Object.keys(allTables),

  // adds new event data to the db, promising the generated seriesId.
  //   eventData is a map of tableName => tableData
  //   the tableData can be one row of data, or multiple rows ( an array. )
  //   each row of data is an object { column_name: column_data }.
  // NOTE: this doesn't do any data validation nor any secret testing.
  insertEventData(tx, eventData) {
    // first: insert the series table first
    return tx('series').insert(eventData.series).then(row => {
      // the series id is autogenerated by the series table
      const seriesId = row[0];
      // then: insert the other tables
      // get all those table names
      const otherTables = Object.keys(eventData).filter(tableName => tableName !== 'series');
      // visit all of them, insert returns a promise
      // make a list of all the promised inserts
      const promises = otherTables.flatMap(tableName => {
        // concat normalizes one or more rows in the data to a list of rows.
        const rows = [].concat(eventData[tableName]).filter(rowData => {
          // filter out any empty rows out of the inserted data.
          return !isEmptyRow(tableName, rowData);
        });
        return rows.map(rowData => {
          rowData.id = seriesId; // every row in every table references the series
          return tx(tableName).insert(rowData);
        });
      });
      return Promise.all(promises).then(_ => seriesId);
    });
  },

  // issues statements to update rows ( or remove them if empty )
  // the eventData format matches the .insert() format ( above )
  // NOTE: this doesn't do any data validation nor any secret testing.
  updateEventData(tx, seriesId, eventData) {
    const updates = Object.keys(eventData).flatMap(tableName => {
      const vals = eventData[tableName];
      const rows = [].concat(vals); // normalize into an array
      return rows.map(rowData =>
        updateOrDelete(tx, tableName, seriesId, rowData));
    });
    return Promise.all(updates);
  },

  // exposed for testing:
  isEmptyRow,
};

function updateOrDelete(tx, tableName, seriesId, rowData) {
  const q =  tx(tableName).where('id', seriesId);
  const extraKey = extraKeys[tableName];
  if (extraKey) {
    q.where(extraKey, rowData[extraKey]);
  }
  // for safety, lets only try to delete rows from the special type tables
  if (extraKey && isEmptyData(rowData, [extraKey])) {
    q.del();
  } else {
    q.update(rowData);
  }
  return q;
};

// returns `true` if every value in the passed row data is empty
// where `tableName` is a known table, and `rowData` is a map of { column_name: column_data }.
// used by insertEventData() to skip inserting data which would generate a row of empty data.
// ( ex. a tag with a false value, or an empty ending location. )
function isEmptyRow(tableName, rowData) {
  const extraKey = extraKeys[tableName];
  return isEmptyData(rowData, ['id', extraKey]);
}

// helper for isEmptyRow
// if the named column isnt in the ignore list,
// and it has a non-zero value; the row has data.
function isEmptyData(rowData, ignore = []) {
  const first = Object.keys(rowData).findIndex(colName =>
    !ignore.includes(colName) && !!rowData[colName]);
  return first < 0;
}
