const allViews = require("./allViews");
const allTriggers = require("./allTriggers");
const { allTables, extraKeys } = require("./allTables");
const TableMaker = require('server/util/tableMaker');

// create tables if they dont already exist
module.exports = {
  // 'image', 'series', etc.
  tableNames: Object.keys(allTables),

  // return a chain of promises
  createTables(db, options = {drop: false}) {
    const context = { tables: allTables, views: allViews, triggers: allTriggers };
    const steps = options.drop ? stages.recreateAll : stages.ensureAll;
    return steps.reduce((prev, stage) => prev.then(_ => {
      const ps = stage(db, context);
      return Promise.all(ps);
    }), Promise.resolve(true));
  },

  // return an array of sql statements
  dumpTableStatements(db) {
    const context = { tables: allTables, views: allViews, triggers: allTriggers };
    return stages.recreateAll.flatMap(stage => {
      const ps = stage(db, context);
      return ps.map(p => {
        const res = p.toSQL();
        return res[0].sql;
      });
    });
  },

  // adds new event data to the db, promising the generated seriesId.
  //   eventData is a map of tableName => tableData
  //   the tableData can be one row of data, or multiple rows ( an array. )
  //   each row of data is an object { column_name: column_data }.
  // NOTE: this doesn't do any data validation nor any secret testing.
  insertEventData(tx, eventData) {
    // first: insert the series table first
    return tx('series').insert(eventData.series).then(row => {
      // the series id is autogenerated by the series table
      const seriesId = row[0];
      // then: insert the other tables
      // get all those table names
      const otherTables = Object.keys(eventData).filter(tableName => tableName !== 'series');
      // visit all of them, insert returns a promise
      // make a list of all the promised inserts
      const promises = otherTables.flatMap(tableName => {
        // concat normalizes one or more rows in the data to a list of rows.
        const rows = [].concat(eventData[tableName]).filter(rowData => {
          // filter out any empty rows out of the inserted data.
          return !isEmptyRow(tableName, rowData);
        });
        return rows.map(rowData => {
          rowData.id = seriesId; // every row in every table references the series
          return tx(tableName).insert(rowData);
        });
      });
      return Promise.all(promises).then(_ => seriesId);
    });
  },

  // issues statements to update rows ( or remove them if empty )
  // the eventData format matches the .insert() format ( above )
  // NOTE: this doesn't do any data validation nor any secret testing.
  updateEventData(tx, seriesId, eventData) {
    const updates = Object.keys(eventData).flatMap(tableName => {
      const vals = eventData[tableName];
      const rows = [].concat(vals); // normalize into an array
      return rows.map(rowData =>
        updateOrDelete(tx, tableName, seriesId, rowData));
    });
    return Promise.all(updates);
  },

  // exposed for testing:
  isEmptyRow,
};

function updateOrDelete(tx, tableName, seriesId, rowData) {
  const q =  tx(tableName).where('id', seriesId);
  const extraKey = extraKeys[tableName];
  if (extraKey) {
    q.where(extraKey, rowData[extraKey]);
  }
  // for safety, lets only try to delete rows from the special type tables
  if (extraKey && isEmptyData(rowData, [extraKey])) {
    q.del();
  } else {
    q.update(rowData);
  }
  return q;
};

// returns `true` if every value in the passed row data is empty
// where `tableName` is a known table, and `rowData` is a map of { column_name: column_data }.
// used by insertEventData() to skip inserting data which would generate a row of empty data.
// ( ex. a tag with a false value, or an empty ending location. )
function isEmptyRow(tableName, rowData) {
  const extraKey = extraKeys[tableName];
  return isEmptyData(rowData, ['id', extraKey]);
}
// helper for isEmptyRow
// if the named column isnt in the ignore list,
// and it has a non-zero value; the row has data.
function isEmptyData(rowData, ignore = []) {
  const first = Object.keys(rowData).findIndex(colName =>
    !ignore.includes(colName) && !!rowData[colName]);
  return first < 0;
}

// returns the promise of a table
function createTable(db, name, tableDesc) {
  return db.query.schema.createTable(name, table => {
    db.config.debug && console.log(`createTable ${name}:`);
    const tm = new TableMaker(db, table);
    for (const colName in tableDesc) {
      const args = [].concat(tableDesc[colName]); // normalize 1 or more arguments into an array of many
      const method = args.shift();            // pop the first one, the "make.something()" function
      method.call(tm, colName, ...args);       // call that function with any remaining arguments
    }
  });
}
// returns the promise of a new view
function createView(db, name, raw) {
  return db.query.schema.createView(name, (view) => {
    return view.as(db.raw(raw));
  });
}
// holds arrays of staging functions: fn(db, {tables, views, triggers})
// which must be called in-order, one at a time.
const stages = {
  ensureAll: [ensureTables, ensureViews, ensureTriggers],
  recreateAll: [dropViews, dropTables, createTables, ensureViews,  ensureTriggers]
}

// a staging function: drops all the tables
// returns an array of promises
function dropTables(db, {tables}) {
  db.config.debug && console.log("dropTables...");
  const names = Object.keys(tables);
  return names.map(n => db.query.schema.dropTableIfExists(n));
}
// a staging function: drops all known views
// returns an array of promises
function dropViews(db, {views}) {
  db.config.debug && console.log("dropViews...");
  const names = Object.keys(views);
  return names.map(n => db.query.schema.dropViewIfExists(n));
}
// a staging function: creates tables, errors if they exist
// returns an array of promises
function createTables(db, {tables}) {
  const names = Object.keys(tables);
  const ps = names.map(n => createTable(db, n, tables[n]));
  db.config.debug && console.log(`create ${ps.length} tables...`);
  return ps;
}
// a staging function: ensure the tables exist, skipping if they already do.
// returns an array of promises
function ensureTables(db, {tables}) {
  db.config.debug && console.log("ensureTables...");
  const names = Object.keys(tables);
  return names.map(n => db.query.schema.hasTable(n).then(exists => {
    if (!exists) {
      return createTable(db, n, tables[n]);
    }
  }));
}
// a staging function: ensure the views exist, recreating if they already do.
// returns an array of promises
function ensureViews(db, {views}) {
  db.config.debug && console.log("ensureViews...");
  return Object.keys(views).map(name => createView(db, name, views[name]));
}
// a staging function: ensure the triggers exist, recreating if they already do.
function ensureTriggers(db, {triggers}) {
  db.config.debug && console.log("ensureTriggers...");
  return Object.values(triggers).map(t => db.query.schema.raw(t));
}

